
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T13:47:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8829696d341e62ca420fcde166434bf10dc68d4",
 "version": "2022.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
